- hosts: ambari-server ambari-agent
  become: true
  vars:
    ambari_version: 2.6.0.0
    ambari_base_version: "{{ ambari_version[0] }}.x"
  tasks:
    - include_vars: file="../vars/{{ ansible_distribution }}.yml"
    - include_vars: file="../roles/ambari-common/vars/ambari-public-repo-root.yml"
      when: ambari_repo_root is not defined
    - include_vars: file="../roles/ambari-common/vars/ambari-public-repo-base-url.yml"
      when: ambari_repo_base_url is not defined
    - include_tasks: ../roles/ambari-common/tasks/install-repo-{{ ansible_os_family }}.yml

- hosts: ambari-server
  become: true
  tasks:
    - include_tasks: ../roles/ambari-server/tasks/install-{{ ansible_os_family }}.yml
    - import_tasks: ../roles/ambari-server/tasks/sudo.yml
      when: remote_ambari_server_user != 'root'
    - import_tasks: ../roles/ambari-server/tasks/setup.yml # must come after sudo stuff
    - import_tasks: ../roles/ambari-server/tasks/start.yml

- hosts: ambari-agent
  become: true
  tasks:
    - include_tasks: ../roles/ambari-agent/tasks/install-{{ ansible_os_family }}.yml
    - import_tasks: ../roles/ambari-agent/tasks/setup.yml # must come before sudo stuff
    - import_tasks: ../roles/ambari-agent/tasks/sudo.yml
      when: remote_ambari_agent_user != 'root'
    - import_tasks: ../roles/ambari-agent/tasks/start.yml
